version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/core"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/packets"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
